import { NextRequest, NextResponse } from "next/server";
import { prisma } from "../../../../lib/prisma";
import { PDFDocument, rgb, StandardFonts } from "pdf-lib";
import fs from "fs";
import path from "path";
import { Decimal } from "@prisma/client/runtime/library";

export const runtime = "nodejs";

/* ──────────────────────────────
   LAYOUT CONSTANTS
────────────────────────────── */
const PAGE_WIDTH = 595;
const PAGE_HEIGHT = 842;

const COL_LABEL = 70;
const COL_VALUE = 300;

const FOOTER_TEXT =
  "Document generated by RW Capital Holding. For informational purposes only. Not an official SWIFT message.";

/* ──────────────────────────────
   HELPERS
────────────────────────────── */
const formatAmount = (value: Decimal | number | string) => {
  const n =
    typeof value === "string"
      ? Number(value.replace(",", "."))
      : typeof value === "number"
      ? value
      : value.toNumber();

  return n.toLocaleString("es-ES", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });
};

const formatDate = (d: Date) =>
  d.toLocaleString("es-ES", {
    dateStyle: "long",
    timeStyle: "short",
  });

/* ──────────────────────────────
   ROUTE
────────────────────────────── */
export async function GET(
  _req: NextRequest,
  context: { params: Promise<{ publicId: string }> }
) {
  const { publicId } = await context.params;

  const tx = await prisma.transaction.findUnique({
    where: { publicId },
    include: {
      events: { orderBy: { occurredAt: "asc" } },
    },
  });

  if (!tx) {
    return NextResponse.json({ error: "Not found" }, { status: 404 });
  }

  /* ──────────────────────────────
     PDF SETUP
  ────────────────────────────── */
  const pdf = await PDFDocument.create();

  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const mono = await pdf.embedFont(StandardFonts.Courier);

  const logoPath = path.join(process.cwd(), "public", "logo.png");
  const logoBytes = fs.readFileSync(logoPath);
  const logo = await pdf.embedPng(logoBytes);

  const drawFooter = (page: any) => {
    page.drawText(FOOTER_TEXT, {
      x: 50,
      y: 50,
      size: 9,
      font,
      color: rgb(0.45, 0.45, 0.45),
    });
  };

  const card = (
    page: any,
    x: number,
    y: number,
    w: number,
    h: number
  ) => {
    page.drawRectangle({
      x,
      y,
      width: w,
      height: h,
      borderColor: rgb(0.85, 0.85, 0.85),
      borderWidth: 1,
    });
  };

  /* ──────────────────────────────
     PAGE 1 — TRANSFER CONFIRMATION
  ────────────────────────────── */
  const p1 = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);

  p1.drawImage(logo, { x: 50, y: 780, width: 140, height: 40 });

  p1.drawText("Transfer confirmation", {
    x: 50,
    y: 735,
    size: 24,
    font: bold,
  });

  p1.drawText(
    "Generated for the client by RW Capital Holding",
    {
      x: 50,
      y: 708,
      size: 10,
      font,
      color: rgb(0.4, 0.4, 0.4),
    }
  );

  p1.drawText("Transfer status", {
    x: 50,
    y: 670,
    size: 14,
    font: bold,
  });

  card(p1, 50, 520, 495, 130);

  const statusRows = [
    ["Transfer ID", tx.publicId],
    ["Partner reference", tx.id],
    ["Wise transfer ID", tx.wiseTransferId],
    ["Status", tx.status],
    ["Created", formatDate(tx.createdAt)],
  ];

  let y = 630;
  statusRows.forEach(([l, v]) => {
    p1.drawText(l, {
      x: COL_LABEL,
      y,
      size: 11,
      font,
      color: rgb(0.45, 0.45, 0.45),
    });
    p1.drawText(v, {
      x: COL_VALUE,
      y,
      size: 11,
      font,
    });
    y -= 24;
  });

  p1.drawText("Transfer overview", {
    x: 50,
    y: 480,
    size: 14,
    font: bold,
  });

  card(p1, 50, 300, 495, 150);

  const overview = [
    ["Amount sent", `${formatAmount(tx.amount)} ${tx.currency}`],
    ["Transfer fees", "—"],
    ["Exchange rate", "—"],
    ["Amount received", `${formatAmount(tx.amount)} ${tx.currency}`],
  ];

  y = 420;
  overview.forEach(([l, v]) => {
    p1.drawText(l, {
      x: COL_LABEL,
      y,
      size: 11,
      font,
      color: rgb(0.45, 0.45, 0.45),
    });
    p1.drawText(v, {
      x: COL_VALUE,
      y,
      size: 11,
      font,
    });
    y -= 28;
  });

  drawFooter(p1);

  /* ──────────────────────────────
     PAGE 2 — PARTIES & BANKING
  ────────────────────────────── */
  const p2 = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);

  p2.drawText("Parties involved", {
    x: 50,
    y: 780,
    size: 16,
    font: bold,
  });

  card(p2, 50, 600, 495, 160);

  y = 720;

  const row = (l: string, v: string) => {
    p2.drawText(l, {
      x: COL_LABEL,
      y,
      size: 11,
      font,
      color: rgb(0.45, 0.45, 0.45),
    });
    p2.drawText(v, {
      x: COL_VALUE,
      y,
      size: 11,
      font,
    });
    y -= 24;
  };

  row("Sending institution", "RW Capital Holding");
  row("Sending bank", "JPM Wise Inc");
  row("Sending SWIFT / BIC", "CHASUS33");
  row("Beneficiary name", tx.recipientName ?? "—");
  row("Receiving bank", "—");
  row("Receiving SWIFT / BIC", "—");

  p2.drawText("Transfer timeline", {
    x: 50,
    y: 520,
    size: 16,
    font: bold,
  });

  card(p2, 50, 300, 495, 190);

  y = 460;
  tx.events.forEach((e) => {
    p2.drawText(
      `• ${formatDate(new Date(e.occurredAt))} — ${e.label}`,
      {
        x: 70,
        y,
        size: 10,
        font,
      }
    );
    y -= 18;
  });

  drawFooter(p2);

  /* ──────────────────────────────
     PAGE 3 — MT103 SAMPLE
  ────────────────────────────── */
  const p3 = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);

  p3.drawText("MT103 sample", {
    x: 50,
    y: 780,
    size: 16,
    font: bold,
  });

  p3.drawText(
    "For informational purposes only – not an official SWIFT message",
    {
      x: 50,
      y: 760,
      size: 9,
      font,
      color: rgb(0.4, 0.4, 0.4),
    }
  );

  card(p3, 40, 120, 515, 600);

  const swift = `
{1:F01TRWIUS35AXXX}
{2:I103CITIUS33XXXN}
{4:
:20:${tx.publicId}
:23B:CRED
:32A:${tx.createdAt
    .toISOString()
    .slice(2, 10)
    .replace(/-/g, "")}${tx.currency}${tx.amount}
:50K:${tx.businessName.toUpperCase()}
:52A:TRWIUS35
:56A:CHASUS33
:59:${tx.recipientName ?? "BENEFICIARY"}
:70:${tx.reference ?? "TRANSFER"}
:71A:SHA
}
`;

  p3.drawText(swift.trim(), {
    x: 55,
    y: 700,
    size: 9.5,
    font: mono,
    lineHeight: 14,
  });

  drawFooter(p3);

  /* ──────────────────────────────
     RESPONSE
  ────────────────────────────── */
  const bytes = await pdf.save();

  return new NextResponse(Buffer.from(bytes), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="transfer-${tx.publicId}.pdf"`,
    },
  });
}
