import { NextRequest, NextResponse } from "next/server";
import { prisma } from "../../../../lib/prisma";
import { PDFDocument, rgb, StandardFonts } from "pdf-lib";
import fs from "fs";
import path from "path";
import { Decimal } from "@prisma/client/runtime/library";

export const runtime = "nodejs";

/* ──────────────────────────────
   LAYOUT CONSTANTS
────────────────────────────── */
const PAGE_WIDTH = 595;
const PAGE_HEIGHT = 842;

const COL_LABEL = 70;
const COL_VALUE = 300;

const FOOTER_TEXT =
  "Document generated by RAVENSWOOD CAPITAL INC. For informational purposes only. Not an official SWIFT message.";

/* ──────────────────────────────
   HELPERS
────────────────────────────── */
const formatAmount = (value: Decimal | number | string) => {
  const n =
    typeof value === "string"
      ? Number(value.replace(",", "."))
      : typeof value === "number"
      ? value
      : value.toNumber();

  return n.toLocaleString("es-ES", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });
};

const formatDate = (d: Date) =>
  d.toLocaleString("es-ES", {
    dateStyle: "long",
    timeStyle: "short",
  });

/* ──────────────────────────────
   ROUTE
────────────────────────────── */
export async function GET(
  _req: NextRequest,
  context: { params: Promise<{ publicId: string }> }
) {
  const { publicId } = await context.params;

  const tx = await prisma.transaction.findUnique({
    where: { publicId },
    include: {
      events: { orderBy: { occurredAt: "asc" } },
    },
  });

  if (!tx) {
    return NextResponse.json({ error: "Not found" }, { status: 404 });
  }

  /* ──────────────────────────────
     PDF SETUP
  ────────────────────────────── */
  const pdf = await PDFDocument.create();

  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const mono = await pdf.embedFont(StandardFonts.Courier);

  const logoPath = path.join(process.cwd(), "public", "logo.png");
  const logoBytes = fs.readFileSync(logoPath);
  const logo = await pdf.embedPng(logoBytes);

  const drawFooter = (page: any) => {
    page.drawText(FOOTER_TEXT, {
      x: 50,
      y: 50,
      size: 9,
      font,
      color: rgb(0.45, 0.45, 0.45),
    });
  };

  const card = (
    page: any,
    x: number,
    y: number,
    w: number,
    h: number
  ) => {
    page.drawRectangle({
      x,
      y,
      width: w,
      height: h,
      borderColor: rgb(0.85, 0.85, 0.85),
      borderWidth: 1,
    });
  };

  /* ──────────────────────────────
     PAGE 1 — TRANSFER CONFIRMATION
  ────────────────────────────── */
  const p1 = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);

  p1.drawImage(logo, { x: 50, y: 780, width: 140, height: 40 });

  // Línea decorativa
  p1.drawRectangle({
    x: 50,
    y: 765,
    width: 495,
    height: 1,
    color: rgb(0.2, 0.4, 0.8),
  });

  p1.drawText("Transfer confirmation", {
    x: 50,
    y: 735,
    size: 24,
    font: bold,
    color: rgb(0.05, 0.05, 0.05),
  });

  p1.drawText(
    "Generated for the client by RAVENSWOOD CAPITAL INC.",
    {
      x: 50,
      y: 708,
      size: 9,
      font,
      color: rgb(0.5, 0.5, 0.5),
    }
  );

  p1.drawText("Transfer status", {
    x: 50,
    y: 670,
    size: 13,
    font: bold,
    color: rgb(0.1, 0.1, 0.1),
  });

  card(p1, 50, 520, 495, 130);

  const statusRows = [
    ["Transfer ID", tx.publicId],
    ["Partner reference", tx.id],
    ["Status", tx.status.toUpperCase()],
    ["Created", formatDate(tx.createdAt)],
  ];

  let y = 630;
  statusRows.forEach(([l, v]) => {
    p1.drawText(l, {
      x: COL_LABEL,
      y,
      size: 10,
      font,
      color: rgb(0.5, 0.5, 0.5),
    });
    p1.drawText(v, {
      x: COL_VALUE,
      y,
      size: 10,
      font: bold,
      color: rgb(0.1, 0.1, 0.1),
    });
    y -= 24;
  });

  p1.drawText("Transfer overview", {
    x: 50,
    y: 480,
    size: 13,
    font: bold,
    color: rgb(0.1, 0.1, 0.1),
  });

  card(p1, 50, 300, 495, 150);

  const overview = [
    ["Amount sent", `${formatAmount(tx.amount)} ${tx.currency}`],
    ["Recipient", tx.recipientName ?? tx.businessName],
    ["Exchange rate", "—"],
    ["Amount received", `${formatAmount(tx.amount)} ${tx.currency}`],
  ];

  y = 420;
  overview.forEach(([l, v]) => {
    p1.drawText(l, {
      x: COL_LABEL,
      y,
      size: 10,
      font,
      color: rgb(0.5, 0.5, 0.5),
    });
    p1.drawText(v, {
      x: COL_VALUE,
      y,
      size: 10,
      font: bold,
      color: rgb(0.1, 0.1, 0.1),
    });
    y -= 28;
  });

  drawFooter(p1);

  /* ──────────────────────────────
     PAGE 2 — PARTIES & BANKING
  ────────────────────────────── */
  const p2 = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);

  p2.drawText("Parties involved", {
    x: 50,
    y: 780,
    size: 16,
    font: bold,
    color: rgb(0.05, 0.05, 0.05),
  });

  card(p2, 50, 600, 495, 160);

  y = 720;

  const row = (l: string, v: string) => {
    p2.drawText(l, {
      x: COL_LABEL,
      y,
      size: 10,
      font,
      color: rgb(0.5, 0.5, 0.5),
    });
    p2.drawText(v, {
      x: COL_VALUE,
      y,
      size: 10,
      font: bold,
      color: rgb(0.1, 0.1, 0.1),
    });
    y -= 24;
  };

  row("Sending institution", "RAVENSWOOD CAPITAL INC.");
  row("Sending bank", "JP Morgan Chase Bank, N.A.");
  row("Sending SWIFT / BIC", "CHASUS33");
  row("Beneficiary name", tx.recipientName ?? "—");
  row("Amount", `${formatAmount(tx.amount)} ${tx.currency}`);
  row("Receiving bank", "—");
  row("Receiving SWIFT / BIC", "—");

  p2.drawText("Transfer timeline", {
    x: 50,
    y: 520,
    size: 16,
    font: bold,
    color: rgb(0.05, 0.05, 0.05),
  });

  // Dibujar timeline con páginas dinámicas
  let timelineY = 460;
  let currentPage = p2;
  let isFirstPage = true;

  // Calcular altura necesaria para los eventos
  const eventHeight = 36; // 16 (fecha) + 20 (descripción)
  const totalEventHeight = tx.events.length * eventHeight;
  let remainingHeight = 460 - 100; // espacio disponible en p2

  tx.events.forEach((e, index) => {
    // Si no hay espacio en la página actual, crear nueva página
    if (timelineY < 120 && !isFirstPage) {
      drawFooter(currentPage);
      currentPage = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
      currentPage.drawText(`Transfer timeline (continued)`, {
        x: 50,
        y: 780,
        size: 16,
        font: bold,
      });
      timelineY = 720;
    } else if (timelineY < 120 && isFirstPage) {
      // Primera página se va a llenar
      drawFooter(currentPage);
      currentPage = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
      currentPage.drawText(`Transfer timeline`, {
        x: 50,
        y: 780,
        size: 16,
        font: bold,
      });
      isFirstPage = false;
      timelineY = 720;
    }

    // Dibujar evento numerado
    currentPage.drawText(`${index + 1}.`, {
      x: 70,
      y: timelineY,
      size: 10,
      font: bold,
      color: rgb(0.1, 0.1, 0.1),
    });

    currentPage.drawText(
      `${formatDate(new Date(e.occurredAt))}`,
      {
        x: 95,
        y: timelineY,
        size: 10,
        font: bold,
        color: rgb(0.2, 0.2, 0.2),
      }
    );
    timelineY -= 18;

    currentPage.drawText(`${e.label}`, {
      x: 95,
      y: timelineY,
      size: 9.5,
      font,
      color: rgb(0.4, 0.4, 0.4),
    });
    timelineY -= 22;
  });

  drawFooter(currentPage);

  /* ──────────────────────────────
     LAST PAGE — MT103 SAMPLE
  ────────────────────────────── */
  const pLast = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);

  pLast.drawText("MT103 sample", {
    x: 50,
    y: 780,
    size: 16,
    font: bold,
    color: rgb(0.05, 0.05, 0.05),
  });

  pLast.drawText(
    "For informational purposes only – not an official SWIFT message",
    {
      x: 50,
      y: 760,
      size: 9,
      font,
      color: rgb(0.5, 0.5, 0.5),
    }
  );

  card(pLast, 40, 120, 515, 600);

  const swift = `{1:F01TRWIUS35AXXX}
{2:I103CITIUS33XXXN}
{4:
:20:${tx.publicId}
:23B:CRED
:32A:${tx.createdAt
    .toISOString()
    .slice(2, 10)
    .replace(/-/g, "")}${tx.currency}${tx.amount}
:50K:${tx.businessName.toUpperCase()}
:52A:RAVENSWOOD CAPITAL INC
:56A:CHASUS33
:59:${tx.recipientName ?? "BENEFICIARY"}
:70:${tx.reference ?? "TRANSFER"}
:71A:SHA
}`;

  pLast.drawText(swift.trim(), {
    x: 60,
    y: 700,
    size: 9,
    font: mono,
    lineHeight: 13,
    color: rgb(0.1, 0.1, 0.1),
  });

  drawFooter(pLast);

  /* ──────────────────────────────
     RESPONSE
  ────────────────────────────── */
  const bytes = await pdf.save();

  return new NextResponse(Buffer.from(bytes), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="transfer-${tx.publicId}.pdf"`,
    },
  });
}
